version: '3.3'

services:
  redis:
    image: redis
    volumes:
      - db_data:/data
  web:
    depends_on:
      - redis
    # COMPLETE HERE
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 200M
      # mode: replicated
      # replicas: 4
volumes:
  db_data: {}