---
- name: Install required packages
  apt:
    name:
      - curl
      - openssh-server 
      - ca-certificates
      - tzdata
      - perl
    state: latest

- name: Install postfix
  apt:
    name: postfix
    state: latest

- name: Enable and start postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Download GitLab install script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
    dest: /tmp/script.deb.sh

- name: Execute GitLab install script
  command: bash /tmp/script.deb.sh

- name: Install GitLab
  apt:
    name: gitlab-ee
  environment:
    EXTERNAL_URL: http://gitlab.local
